Update script for version 1.2 with enhancements

diff --git a/jas b/jas
--- a/jas
+++ b/jas
@@ -6,7 +6,15 @@
 # Colors for ASCII art
 # -------------------
 
+RED="\e[31m"
+GREEN="\e[32m"
+YELLOW="\e[33m"
+BLUE="\e[34m"
+CYAN="\e[36m"
+BOLD="\e[1m"
 RESET="\e[0m"
+
+#ASCII art with color cycling
 COLORS=(
 "255;120;0"
 "255;80;80"
@@ -34,7 +42,9 @@ done <<'EOF'
 EOF
 
 
-echo "    Alpha version 1.1 - Author: Jasper - License: MIT"
+echo -e "${BOLD}${YELLOW}  Version 1.2 - Author: Jasper - License: MIT${RESET}"
+
+# End ascii art, start of toolbox code
 
 # -------------------
 # Network Tools Submenu
@@ -42,36 +52,49 @@ echo "    Alpha version 1.1 - Author: Jasper - License: MIT"
 network_tools() {
     while true; do
         PS3="Network Tools Menu: "
-        options=("Whois" "Ping" "Trace" "DNS info" "get IP" "Geolocate" "Back")
+        options=("Whois" "Ping" "Trace" "DNS info" "get IP" "IP osint" "Back")
         select opt in "${options[@]}"; do
             case $REPLY in
                 1)
                     # Whois lookup
                     echo -n "Enter domain (ex: example.com): "
-                    read -r domain
-                    whois "$domain"
+                    read -r domain # read domain input from user
+                    echo -e "${GREEN}[+] Performing Whois lookup for $domain...${RESET}"
+                    sleep 0.5
+                    whois "$domain" # Perform whois lookup and display results
                     ;;
                 2)
                     echo -n "Enter item to ping: "
-                    read -r itemping
-                    ping "$itemping"
+                    read -r itemping # read ping target input from user
+                    echo -e "${GREEN}[+] Pinging $itemping...${RESET}"
+                    sleep 0.5
+                    ping "$itemping" # Perform ping and display results
                     ;;
                 3)
                     echo -n "Enter domain to trace: "
-                    read -r domaintrace
-                    traceroute "$domaintrace"
+                    read -r domaintrace # read trace target input from user
+                    echo -e "${GREEN}[+] Tracing route to $domaintrace...${RESET}"
+                    sleep 0.5
+                    traceroute "$domaintrace" # Perform traceroute and display results
                     ;;
                 4)
                     echo -n "Enter domain to get DNS info: "
-                    read -r domaindns
-                    dig "$domaindns"
+                    read -r domaindns # read DNS target input from user
+                    echo -e "${GREEN}[+] Getting DNS info for $domaindns...${RESET}"
+                    sleep 0.5
+                    dig "$domaindns" # Perform DNS lookup and display results
                     ;;
                 5)
-                    curl ifconfig.me
+                    echo -e "${GREEN}[+] Fetching public IP...${RESET}"
+                    sleep 0.5
+                    curl ifconfig.me # Fetch and display public IP address
                     ;;
                 6)
-                    ip_geo() {
-                    read -p "Enter IP or domain: " target
+                    ip_osint() {
+                    read -p "Enter IP or domain: " target # read target input from user
+                    
+                    echo -e "${GREEN}[+] Fetching OSINT for $target...${RESET}"
+                    sleep 0.5
 
                     data=$(curl -s ipinfo.io/$target)
 
@@ -82,13 +105,14 @@ network_tools() {
                     echo "ISP:      $(echo $data | jq -r '.org')"
                     echo "Timezone: $(echo $data | jq -r '.timezone')"
                 }
-                    ip_geo
+                    ip_osint # Perform IP OSINT lookup and display results
                     ;;
                 7)
-                    return  # Back to main menu
+                    echo -e "${GREEN}[+] Returning to main menu...${RESET}" 
+                    return  
                     ;;
                 *)
-                    echo "Invalid option"
+                    echo -e "${RED} [!] Invalid option${RESET}   " # Handle invalid input and prompt user again
                     ;;
             esac
         done
@@ -101,51 +125,86 @@ network_tools() {
 system_tools() {
     while true; do
         PS3="System Tools Menu: "
-        options=("Updating all apps" "See system information" "Back")
+        options=("Updating all apps" "See system information" "Paranoia mode" "Back")
         select opt in "${options[@]}"; do
             case $REPLY in
                 1)
+                    echo -e "${GREEN}[+] Starting update process...${RESET}"
+                    sleep 0.5
                     echo "Updating all apps..."
                     # update APT
                     echo "Updating all APT packages..."
                     echo
-                    sudo apt update && sudo apt upgrade -y
+                    sudo apt update && sudo apt upgrade -y # Update APT packages and display results
                     echo
-                    echo "APT packages updated"
+                    echo -e "${GREEN}[+] APT packages updated${RESET}"
                     echo 
                     # update flatpak
                     echo "Updating all flatpak packages..."
                     echo
-                    flatpak update -y
+                    flatpak update -y # Update flatpak packages and display results 
                     echo
-                    echo "flatpak updated"
+                    echo -e "${GREEN}[+] flatpak updated${RESET}"
                     echo 
                     # update snap
                     echo "Updating all snap packages..."
                     echo
-                    sudo snap refresh
+                    sudo snap refresh # Update snap packages and display results
                     echo
                     upgradable=$(snap list --upgradable)
                     if [ -z "$upgradable" ]; then
-                    echo "No upgradable Snap packages found."
+                    echo -e "${RED}[!] No upgradable Snap packages found.${RESET}"
                     else
                     echo "Upgradable Snap packages:"
                     echo "$upgradable" 
                     echo "Updating upgradable Snap packages..."
-                    sudo snap refresh --all
+                    sudo snap refresh --all # Update all snap packages, including upgradable ones
                     echo 
-                    echo "All upgradable Snap packages have been updated."
+                    echo -e "${GREEN}[+] All upgradable Snap packages have been updated.${RESET}"
                     echo
                     fi
             ;;
                 2)
-                    fastfetch
+                    echo -e "${GREEN}[+] Gathering system information...${RESET}"
+                    sleep 0.5
+                    fastfetch # Display system information using fastfetch
                     ;;
-                3)
+                3)   
+                    confirm_paranoia() {
+                    echo -e "[!] WARNING: PARANOIA MODE IS EXTREMELY INVASIVE"
+                    echo "Type EXACTLY: ENABLE PARANOIA MODE"
+                    read -r input
+
+                    if [[ "$input" != "ENABLE PARANOIA MODE" ]]; then
+                    echo -e "${RED}[!] Confirmation failed. Aborting.${RESET}"
+                    exit 1
+                    fi
+                    }
+
+                    confirm_paranoia
+
+                    echo -e "${GREEN}[+] Enabling Paranoia mode...${RESET}"
+                    sleep 0.5
+
+                    sudo iptables -P OUTPUT DROP # Drop all outgoing traffic by default
+                    sudo iptables -A OUTPUT -d 127.0.0.1 -j ACCEPT # Allow localhost
+                    nmcli networking off # Disable NetworkManager
+
+                    shred -u ~/.bash_history 2>/dev/null # Securely delete bash history
+                    history -c # Clear current session history
+                    sudo find /tmp -type f -exec shred -u {} \; 2>/dev/null # Securely delete temporary files
+
+                    sudo modprobe -r uvcvideo 2>/dev/null # Disable webcam
+                    sudo modprobe -r snd_hda_intel 2>/dev/null # Disable microphone
+
+                    echo -e "${GREEN}[+] Paranoia mode enabled.${RESET}"
+                    ;;
+                4)
+                    echo -e "${GREEN}[+] Returning to main menu...${RESET}"
                     return
                     ;;
                 *)
-                    echo "Invalid option"
+                    echo -e "${RED} [!] Invalid option${RESET}   " # Handle invalid input and prompt user again
                     ;;
             esac
         done
@@ -155,10 +214,11 @@ system_tools() {
 # -------------------
 # Privacy/Security Tools Submenu
 # -------------------
+
 privacy_tools() {
     while true; do
         PS3="Privacy/Security Menu: "
-        options=("Secure empty trash" "Securely overwrite free space" "Check for rootkits" "Removing file" "Generate secure password" "Remove temporary files" "Back")
+        options=("Securely wipe trash" "Securely overwrite free space" "Peform system audit" "Peform system cleanup" "Check for rootkits" "Remove temporary files" "Generate secure password" "Delete file"  "Exit")
         select opt in "${options[@]}"; do
             case $REPLY in
                 1)
@@ -174,68 +234,94 @@ privacy_tools() {
                     # Confirm deletion
                     read -rp "Confirm deletion (y/n): " confirm
                     if [[ "$confirm" != "y" ]]; then
-                        echo "Aborted."
+                        echo -e "${RED}[!] Deletion aborted.${RESET}"
                         continue
                     fi
 
                     # Securely delete files
+                    echo -e "${GREEN}[+] Securely deleting trash...${RESET}"
+                    sleep 0.5
                     echo "Deleting files..."
                     srm -v -r "${TRASH_FILES}/"*
 
-                    echo "Securely deleting trash info..."
+                    echo -e "${GREEN}[+] Securely deleting trash info...${RESET}"
+                    sleep 0.5
                     srm -v -r "${TRASH_INFO}/"*
 
                     # Completed status
-                    echo "Completed"
+                    echo -e "${GREEN}[+] Deletion completed.${RESET}"
                     ;;
             
                 2)
-                    echo "Securely overwriting free space..."
+                    echo -e "${GREEN}[+] Securely overwriting free space...${RESET}"
                     # Get the root partition
                     root_partition=$(df / | tail -1 | awk '{print $1}')
                     
                     # Check if srm is installed
                     if ! command -v srm &> /dev/null; then
-                        echo "srm command not found. Please install it to use this feature."
+                        echo -e "${RED}[!] srm command not found. Please install it to use this feature.${RESET}"
                         continue
                     fi
                     
                     # Securely overwrite free space
-                    echo "Overwriting free space on $root_partition..."
+                    echo -e "${GREEN}[+] Overwriting free space on $root_partition...${RESET}"
                     srm -v -z -r --free "$root_partition"
                     
-                    echo "Free space securely overwritten."
+                    echo -e "${GREEN}[+] Free space securely overwritten.${RESET}"
                     ;;
                 3)
-                    echo "Checking for rootkits with chkrootkit..."
-                    chkrootkit 
-                    ;;
+                    echo -e "${GREEN}[+] Performing system audit with Lynis...${RESET}"
+                    sleep 0.5
+                    echo
+                    sudo lynis audit system # Perform system audit with Lynis and display results
+                    echo
+                    echo -e "${GREEN}[+] System audit completed.${RESET}"
+                    ;;    
                 4)
+                    echo -e "${GREEN}[+] Running BleachBit...${RESET}"
+                    sleep 0.5
+                    sudo bleachbit # Run BleachBit with root privileges and display results
+                    echo -e "${GREEN}[+] BleachBit cleanup completed.${RESET}"
+                    ;;
+                5)
+                    echo -e "${GREEN}[+] Checking for rootkits with chkrootkit...${RESET}"
+                    chkrootkit # Check for rootkits with chkrootkit and display results
+                    echo -e "${GREEN}[+] Rootkit check completed.${RESET}"
+                    ;;  
+                6)
+                    echo -e "${GREEN}[+] Removing temporary files...${RESET}"
+                    rm -rf /tmp/* # Remove all files in /tmp directory
+                    echo -e "${GREEN}[+] Temporary files removed.${RESET}"
+                    ;;  
+                7)
+                    echo -e "${GREEN}[+] Generating secure password...${RESET}"
+                    sleep 0.5
+                    echo 
+                    openssl rand -base64 12 # Generate and display a secure random password
+                    echo -e "${GREEN}[+] Password generation completed.${RESET}"
+                    ;;  
+
+                8)    
                     echo -n "Enter file: "
                     read -r file
 
                     if [[ -z "$file" ]]; then
-                    echo "No file entered."
+                    echo -e "${RED}[!] No file entered.${RESET}"
                     elif [[ ! -f "$file" ]]; then
-                    echo "File does not exist."
+                    echo -e "${RED}[!] File does not exist.${RESET}"
                     else
-                    echo "Running shred for: $file"
-                    shred -u -v -n 5 "$file"
+                    echo -e "${GREEN}[+] Running shred for: $file${RESET}"
+                    shred -u -v -n 5 "$file" # Securely delete the specified file with 5 passes and display results
+                    echo -e "${GREEN}[+] File securely deleted.${RESET}"
                     fi
                     ;; 
-                5)
-                    openssl rand -base64 12
-                    ;;    
-                6)
-                    echo "Removing temporary files..."
-                    rm -rf /tmp/*
-                    echo "Temporary files removed."
-                    ;;    
-                7)
+                
+                9)
+                    echo -e "${GREEN}[+] Returning to main menu...${RESET}"
                     return
                     ;;
                 *)
-                    echo "Invalid option"
+                    echo -e "${RED}[!] Invalid option.${RESET}" # Handle invalid input and prompt user again
                     ;;
             esac
         done
@@ -285,9 +371,9 @@ SOFTWARE.
 EOF
             ;;
             q) 
-            echo "Exiting."; exit 0 ;;
+            echo -e "${GREEN}[+] Exiting.${RESET}"; exit 0 ;;
             *) 
-            echo "Invalid option" ;;
+            echo -e "${RED}[!] Invalid option.${RESET}" ;;
         esac
     done
 done
