Complete show_weather

diff --git a/peregine b/peregine
--- a/peregine
+++ b/peregine
@@ -1004,8 +1004,30 @@ update_apps() {
 }
 # Todo: add more system apps
 show_weather() {
-    # Placeholder
-    echo "Under construction"
+    echo -e "${DIVIDER}"
+    echo "[->] Checking dependencies"
+
+    if ! command -v curl >/dev/null 2>&1; then
+        echo "${RED}[!]${RESET} Required dependencie not installed"
+        echo "Install with: sudo apt install curl"
+        return 1
+    fi
+
+    echo -e "${GREEN}[+]${RESET} Dependencies are installed"
+    echo 
+
+    output=$(curl -s --max-time 5 wttr.in 2>&1)
+    status=$?
+
+    if [[ $status -ne 0 ]]; then
+        echo -e "${RED}[!]${RESET} Failed to connect to weather website: $output"
+        return 1
+    else
+        echo -e "${GREEN}[+]${RESET} The wheather is: ${CYAN}$output${RESET}"
+    fi
+
+    echo "[->] Command executed"
+    echo -e "${DIVIDER}"
 }
 count_lines_file() {
     # Placeholder
@@ -2646,6 +2668,8 @@ help() {
             echo "  You will be prompted to choose your package manager."
             ;;
         show_weather)
+            echo -e "${CYAN}show_weather${RESET}"
+            echo "  Show fancy weather in your ternimal using curl"
         ;;
         count_lines_file)
         ;;
